# Generated by Django 2.1.2 on 2018-11-01 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idciudad', models.IntegerField(primary_key=True, serialize=False, verbose_name='idciudad')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idcomuna', models.IntegerField(primary_key=True, serialize=False, verbose_name='idcomuna')),
                ('descripcion', models.TextField()),
                ('idciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idestado', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='nombre')),
                ('raza', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('foto', models.FileField(upload_to='')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idregion', models.IntegerField(primary_key=True, serialize=False, verbose_name='idregion')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='rut')),
                ('nombre', models.TextField(max_length=45)),
                ('apellido', models.TextField(max_length=45)),
                ('correo', models.TextField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ciudad')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idtipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='idtipo')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='tipousuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoUsuario'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='idregion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region'),
        ),
    ]
