# Generated by Django 2.1.2 on 2018-11-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181108_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='apellido',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='registro',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
    ]
