# Generated by Django 2.1.2 on 2018-11-08 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181108_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('rut', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=45)),
                ('idciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ciudad')),
                ('idcomuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comuna')),
                ('idregion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region')),
            ],
        ),
    ]
