# Generated by Django 2.1.2 on 2018-11-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='idciudad',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='idcomuna',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='idregion',
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
